logging:
  path: ./log/

spring:
  datasource:
    url: jdbc:mysql://59.203.218.244:3307/exam_system?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Aqtest@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #数据库索引
    database: ${REDIS_DB:1}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000

# 文件存储路径
file:
  mac:
    path: ~/file/examsystem/
    avatar: ~/avatar/examsystem/
  linux:
    path: /home/eladmin/file/
    avatar: /home/eladmin/avatar/
  windows:
    path: C:\eladmin\file\
    avatar: C:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
elasticsearch:
  ip: 127.0.0.1
  port: 9300
  pool: 5
  cluster:
    name: my-application